from django.urls import path

from .views import (
    about_fe,
    blogs,
    careers,
    contact,
    engineer,
    help_center,
    help_center_2,
    home,
    home_2,
    request_service,
    vendor,
    vendor_responses,
    privacy_policy,
    disclaimer,
    term_condition,
    profile,
    customer_contactus,
    how_it_works,
    customer,
    stay_updated_subscribe,
    contact_submit,
    sales_enquiry_submit
)

urlpatterns = [
    path('', home, name='home'),
    path('home-2/', home_2, name='home_2'),
    path('engineer/', engineer, name='engineer'),
    path('vendor/', vendor, name='vendor'),
    path('about-fe/', about_fe, name='about_fe'),
    path('careers/', careers, name='careers'),
    path('blogs/', blogs, name='blogs'),
    path('contact/', contact, name='contact'),
    path('contact-submit/', contact_submit, name='contact_submit'),
    path('help-center/', help_center, name='help_center'),
    path('help-center-2/', help_center_2, name='help_center_2'),
    path('vendor-responses/', vendor_responses, name='vendor_responses'),
    path('services/request_service/', request_service, name='request_service'),
    path('privacy-policy/', privacy_policy, name='privacy-policy'),
    path('term-condition/', term_condition, name='term_condition'),
    path('disclaimer/', disclaimer, name='disclaimer'),
    path('profile/', profile, name='profile'),
    path('customer-contactus/', customer_contactus, name='customer_contactus'),
    path('how-it-works/', how_it_works, name='how_it_works'),
    path('customer/', customer, name='customer'),
    path('stay-updated-subscribe/', stay_updated_subscribe, name='stay_updated_subscribe'),
    path('sales-enquiry/', sales_enquiry_submit, name='sales_enquiry_submit'),
]