from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('bookings/', views.bookings, name='bookings'),
    path('saved_address/', views.saved_address, name='saved_address'),
    path('payment_methods/', views.payment_methods, name='payment_methods'),
    path('support_center/', views.support_center, name='support_center'),
    path('settings/', views.settings, name='settings'),
    path('invoice/', views.invoice, name='invoice'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('home-2/', views.home_2, name='home_2'),
    path('engineer/', views.engineer, name='engineer'),
    path('vendor/', views.vendor, name='vendor'),
    path('about-fe/', views.about_fe, name='about_fe'),
    path('careers/', views.careers, name='careers'),
    path('blogs/', views.blogs, name='blogs'),
    path('contact/', views.contact, name='contact'),
    path('contact-submit/', views.contact_submit, name='contact_submit'),
    path('help-center/', views.help_center, name='help_center'),
    path('help-center-2/', views.help_center_2, name='help_center_2'),
    path('vendor-responses/', views.vendor_responses, name='vendor_responses'),
    path('services/request_service/', views.request_service, name='request_service'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('term-condition/', views.term_condition, name='term_condition'),
    path('disclaimer/', views.disclaimer, name='disclaimer'),
    path('profile/', views.profile, name='profile'),
    path('customer-contactus/', views.customer_contactus, name='customer_contactus'),
    path('how-it-works/', views.how_it_works, name='how_it_works'),
    path('customer/', views.customer, name='customer'),
    path('stay-updated-subscribe/', views.stay_updated_subscribe, name='stay_updated_subscribe'),
    path('sales-enquiry/', views.sales_enquiry_submit, name='sales_enquiry_submit'),
    path('articles/', views.articles, name='articles'),
    path('job-description/', views.job_description, name='job_description'),
    path('news/', views.news, name='news'),
]